[package]
name = "authorization"
version = "0.1.0"
edition = "2021"

[dependencies]
environment = { path = "../environment" }
errors = { path = "../errors" }
database = { path = "../database" }
repository = { path = "../repository" }
state = { path = "../state" }

base64 = "0.21.0"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
uuid = { version = "1.3.0", features = ["serde", "v4"] }
chrono = "0.4.38"
redis = { version = "0.27.4", features = ["tokio-comp"] }
jsonwebtoken = "9.3.0"




