[package]
name = "router"
version = "0.1.0"
edition = "2021"

[dependencies]
environment = { path = "../environment" }
errors = { path = "../errors" }
database = { path = "../database" }
repository = { path = "../repository" }
services = { path = "../services" }
authorization = { path = "../authorization"}
state = { path = "../state" }
file_storage = { path = "../file_storage" }


axum = {version = "0.7.5",features = ["multipart"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
axum-extra = { version = "0.9.0", features = ["cookie"] }
argon2 = "0.5.0"
futures = "0.3.31"
chrono = "0.4.38"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
uuid = { version = "1.3.0", features = ["serde", "v4"] }
surrealdb = "2.0.4"
rand_core = { version = "0.6.4", features = ["std"] }
redis = { version = "0.27.4", features = ["tokio-comp"] }
time = "0.3.20"









