[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb = "2.0.4"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
axum = {version = "0.7.5"}
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
environment = { path = "../environment" }
errors = { path = "../errors" }

